# -*- coding: utf-8 -*-
"""clase 27

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/186WogwseAY0LExsDsIC6ghS-YBflruaJ
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

df = pd.read_csv("Fitness_Classification.csv")

df.head()

df.describe()

df.isna().sum()

df["smokes"] = df["smokes"].astype(str).str.lower()
df["smokes"] = df["smokes"].replace({"si": 1, "sí": 1, "yes": 1, "1": 1,"no": 0, "0": 0}).astype(float)

df["gender"] = df["gender"].replace({"M": 1, "F": 0})

df = df.fillna(df.mean(numeric_only=True))

print("Dataset limpio:")
df.head()

plt.figure(figsize=(12,8))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Mapa de calor de correlación")
plt.show()

X = df.drop("is_fit", axis=1)
y = df["is_fit"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
modelo = DecisionTreeClassifier(max_depth=5)
modelo.fit(X_train, y_train)

y_pred = modelo.predict(X_test)

print("Accuracy del modelo:", accuracy_score(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, cmap="Blues", fmt="d")
plt.title("Matriz de Confusión")
plt.xlabel("Predicción")
plt.ylabel("Real")
plt.show()

ejemplo = X_test.iloc[0:1]
print("Ejemplo de predicción:")
print("Datos:", ejemplo)
print("Predicción:", modelo.predict(ejemplo)[0])

from sklearn.tree import plot_tree
plt.figure(figsize=(20,10))
plot_tree(modelo, feature_names=X.columns, class_names=['No en forma','En forma'], filled=True, rounded=True, fontsize=10)
plt.show()

from sklearn.model_selection import GridSearchCV

params = {'criterion': ['gini','entropy'], 'max_depth':[3,5,7]}
grid = GridSearchCV(DecisionTreeClassifier(random_state=1614006), params, cv=5, scoring='accuracy')
grid.fit(X_train, y_train)
print("Mejor params (gini/entropy):", grid.best_params_)
print("Mejor score CV:", grid.best_score_)

ej = X_test.iloc[0:1]
print("Ejemplo (datos):")
display(ej)
print("Predicción (0=no,1=si):", grid.best_estimator_.predict(ej)[0])